server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: produto-route
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        - id: pedido-route
          uri: http://localhost:8082
          predicates:
            - Path=/pedidos/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG